export { Header } from '@/components/Header/Header'
export { SEO } from '@/components/SEO/SEO'
export { Top } from '@/components/Top/Top'
export { Blogs } from '@/components/Blogs/Blogs'
export { SectionTitle } from '@/components/Common/SectionTitle'
export { Activities } from '@/components/Activities/Activities'
